feature: Add messenger page
JimTheCat/MeowHub pull request #67
Opened 2024-12-02 21:07 UTC by JimTheCat

2024-12-02 21:07 UTC, JimTheCat commented
Task linked: [CU-8696pcyn4 Create messages page](https://app.clickup.com/t/8696pcyn4)

2024-12-03 21:03 UTC, JimTheCat commented
This is how it looks like:
![image](https://github.com/user-attachments/assets/26143f19-8376-4329-a6ef-bf3d585111bb)

2024-12-04 11:21 UTC, KinTrae requested changes

2024-12-06 18:18 UTC, KinTrae requested changes

2024-12-06 18:18 UTC, KinTrae commented on frontend/src/Pages/Messenger/Messenger.tsx
> +      }, getCryptoRandom() * 300000 + 60000); // Aktywność co 1-6 minut
i still see here polish comments

2024-12-06 18:18 UTC, KinTrae commented on frontend/src/Pages/Messenger/Messenger.tsx
> +      return array[0] / (0xFFFFFFFF + 1); // Normalizacja do zakresu 0–1
and here

2024-12-07 15:13 UTC, KinTrae approved these changes

2024-12-07 15:13 UTC, merged